name: SimpleLuckPermsFormatter
main: de.nycode.slpf.SimpleLuckPermsFormatter
version: 1.1.0
api-version: 1.18
authors:
  - NyCode
  - StckOverflw
website: https://github.com/CherryCave/SimpleLuckPermsFormatter
depend:
  - LuckPerms
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.20"